services:
  - type: web
    name: cloud_computing
    runtime: node
    repo: https://github.com/Bania2001/blue_print.git
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: data_base
    region: frankfurt
    plan: free
    databasesName: cloud
    user: cloud
